version: '3.1'

services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123$
      JDBC_PARAMS: useSSL=false

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
